### ISSUE TITLE
[npm ci] Does not throw when out of sync

### ISSUE THREAD

**Issue by screendriver** [peterjuras/npm-workspaces-lifecycle-scripts-issue#1]
npm v7 also has issues when you run `npm ci` and your `package-lock.json` and `package.json` is out of sync: it does not throw an error anymore.

**Comment by peterjuras** [comment]
See [this comment in another issue](https://github.com/peterjuras/npm-workspaces-lifecycle-scripts-issue/issues/2#issuecomment-709859628).
