### ISSUE TITLE
[npm i] Fails on first installation but not on second one

### ISSUE THREAD

**Issue by screendriver** [peterjuras/npm-workspaces-lifecycle-scripts-issue#2]
In one of my repositories `npm i` fails on the first try but succeeds on the second run 🤔

**Comment by peterjuras** [comment]
Hi,

I forgot to set a proper description, but this repo only exists as a sample for [an issue I found with npm](https://github.com/npm/cli/issues/1965).

It's very worrying though to see that install fails or that npm ci (#1) does not work as expected anymore. It's probably best to open these issues in the [npm/cli](https://github.com/npm/cli/issues/) repo directly.
